# Generated by Django 2.2.3 on 2020-05-10 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YouthCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=100)),
                ('place_of_center', models.CharField(max_length=100)),
                ('stsus_of_center', models.CharField(choices=[('WR', 'worked'), ('DS', 'destroyed'), ('OS', 'out_of_service'), ('NB', 'newly_build')], default='WR', max_length=100)),
                ('image', models.FileField(default='default.jpg', upload_to='profile_pics')),
                ('center_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('center_total_youth', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kiros', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
