# Generated by Django 2.2.3 on 2020-05-10 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YouthCenter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youthcenter',
            old_name='image',
            new_name='file',
        ),
    ]
