# Generated by Django 2.2.3 on 2020-05-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouthCenter', '0002_auto_20200510_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.FileField(upload_to='pictures')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
